// fake data generated by chatgpt
const FAKE_SEARCH_DATA = [
  {
    id: 127,
    title: "ALISA PUERTO KINO",
    image: "https://itzimna.s3.amazonaws.com/media/property-images/alisa_kino-_Itzimna_real_estate_1.jpeg",
    description: "With Itzimna Real Estate, invest in residential lots at Puerto Kino, San Crisanto. Enjoy high appreciation, luxury amenities, and legal certainty on the idyllic Emerald Coast of Yucatan.",
    extra: {
      price: "1,372,173.68",
      meters: 644.97
    },
    date: "2025-06-24T12:05:46.243302-06:00",
    type: "property"
  },
  {
    id: 18,
    title: "PUERTO KINO",
    image: "https://itzimna.s3.amazonaws.com/media/property-images/puerto_kino-_Itzimna_Real_estate__1.jpeg",
    description: "Puerto Kino San Crisanto, Yucatán: Your coastal sanctuary. Premium residential lots near Mérida. Nature, tranquility, and high appreciation. Flexible financing!",
    extra: {
      price: "623,169.36",
      meters: 307.89
    },
    date: "2025-06-24T11:18:30.169227-06:00",
    type: "property"
  },
  {
    id: 45,
    title: "HERMOSO DESARROLLO RESIDENCIAL MÉRIDA CENTRO",
    image: "/images/home-banner.jpg",
    description: "Exclusivo desarrollo residencial ubicado en el corazón de Mérida, con amenidades de primer nivel y acabados de lujo. Perfecto para familias que buscan comodidad y elegancia.",
    extra: {
      price: "2,850,000.00",
      meters: 850.00
    },
    date: "2025-06-23T15:30:15.123456-06:00",
    type: "property"
  },
  {
    id: 67,
    title: "DEPARTAMENTOS DE LUJO FRENTE AL MAR PROGRESO",
    image: "/images/home-banner.jpg",
    description: "Modernos departamentos con vista al mar en el puerto de Progreso. Ideal para inversión o residencia de descanso con acceso directo a la playa.",
    extra: {
      price: "3,200,000.00",
      meters: 120.50
    },
    date: "2025-06-22T09:45:30.654321-06:00",
    type: "property"
  },
  {
    id: 89,
    title: "TERRENOS COMERCIALES ZONA NORTE MÉRIDA",
    image: "/images/home-banner.jpg",
    description: "Excelente oportunidad de inversión en terrenos comerciales ubicados en la zona de mayor crecimiento de Mérida para desarrollos comerciales.",
    extra: {
      price: "1,500,000.00",
      meters: 2000.00
    },
    date: "2025-06-21T14:20:45.987654-06:00",
    type: "property"
  },
  {
    id: 112,
    title: "CASA COLONIAL RESTAURADA CENTRO HISTÓRICO",
    image: "/images/home-banner.jpg",
    description: "Hermosa casa colonial completamente restaurada en el centro histórico de Mérida. Combina la arquitectura tradicional con comodidades modernas.",
    extra: {
      price: "4,800,000.00",
      meters: 450.75
    },
    date: "2025-06-20T11:10:20.456789-06:00",
    type: "property"
  },
  {
    id: 134,
    title: "CONDOMINIO MODERNO CON ALBERCA MONTEJO",
    image: "/images/home-banner.jpg",
    description: "Elegante condominio en la prestigiosa zona de Montejo. Incluye alberca, gimnasio, área de juegos y seguridad las 24 horas.",
    extra: {
      price: "2,100,000.00",
      meters: 180.25
    },
    date: "2025-06-19T16:35:10.789123-06:00",
    type: "property"
  },
  {
    id: 156,
    title: "VILLA DE LUJO MÉRIDA NORTE",
    image: "/images/home-banner.jpg",
    description: "Espaciosa villa de lujo con jardín privado y piscina. Ubicada en zona residencial exclusiva con fácil acceso a centros comerciales.",
    extra: {
      price: "5,200,000.00",
      meters: 650.00
    },
    date: "2025-06-18T13:25:55.321654-06:00",
    type: "property"
  },
  {
    id: 178,
    title: "PENTHOUSE VISTA PANORÁMICA ALTABRISA",
    image: "/images/home-banner.jpg",
    description: "Exclusivo penthouse con vistas panorámicas de la ciudad. Amplias terrazas, acabados premium y ubicación privilegiada en Altabrisa.",
    extra: {
      price: "7,500,000.00",
      meters: 320.80
    },
    date: "2025-06-17T10:15:40.147258-06:00",
    type: "property"
  },
  {
    id: 201,
    title: "HACIENDA RESTAURADA AFUERAS MÉRIDA",
    image: "/images/home-banner.jpg",
    description: "Histórica hacienda completamente restaurada con amplios jardines y piscina. Perfecta para eventos o residencia de lujo.",
    extra: {
      price: "12,000,000.00",
      meters: 1500.00
    },
    date: "2025-06-16T08:50:25.852741-06:00",
    type: "property"
  },
  {
    id: 223,
    title: "LOFT INDUSTRIAL ZONA CULTURAL",
    image: "/images/home-banner.jpg",
    description: "Moderno loft de estilo industrial en la zona cultural de Mérida. Espacios abiertos, techos altos y diseño contemporáneo.",
    extra: {
      price: "1,800,000.00",
      meters: 95.50
    },
    date: "2025-06-15T17:40:15.963852-06:00",
    type: "property"
  },
  {
    id: 245,
    title: "DESARROLLO SUSTENTABLE TEMOZON NORTE",
    image: "/images/home-banner.jpg",
    description: "Innovador desarrollo sustentable con tecnología eco-friendly. Paneles solares, sistemas de captación de agua y áreas verdes.",
    extra: {
      price: "2,600,000.00",
      meters: 220.30
    },
    date: "2025-06-14T12:30:05.741963-06:00",
    type: "property"
  }
]

/**
 * Fake search API function - matches real API structure
 * @param {string} query - Search query
 * @param {number} page - Page number (default: 1)
 * @param {number} limit - Results per page (default: 6)
 * @returns {Promise<Object>} Search results matching real API structure
 */
export const globalSearchAPI = async (query = "", page = 1, limit = 6) => {
  let filteredResults = FAKE_SEARCH_DATA
  
  // Filter by query if provided
  if (query.trim()) {
    const searchTerm = query.toLowerCase()
    filteredResults = FAKE_SEARCH_DATA.filter(item => 
      item.title.toLowerCase().includes(searchTerm) ||
      item.description.toLowerCase().includes(searchTerm)
    )
  }
  
  // Calculate pagination
  const totalResults = filteredResults.length
  const totalPages = Math.ceil(totalResults / limit)
  const startIndex = (page - 1) * limit
  const endIndex = startIndex + limit
  const results = filteredResults.slice(startIndex, endIndex)
  
  // Build next/previous URLs
  const baseUrl = `${process.env.NEXT_PUBLIC_HOST || 'http://localhost:3000'}/search/`
  const nextPage = page < totalPages ? page + 1 : null
  const prevPage = page > 1 ? page - 1 : null
  
  const next = nextPage ? `${baseUrl}?q=${encodeURIComponent(query)}&page=${nextPage}` : null
  const previous = prevPage ? `${baseUrl}?q=${encodeURIComponent(query)}&page=${prevPage}` : null
  
  
  return {
    count: totalResults,
    next,
    previous,
    results
  }
} 